colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true

enableCodeCopy = true

highlightCurrentMenuArea = true
enableA11y = false
disableTextInHeader = false

disableImageOptimization = false
disableImageZoom = false

enableStructuredBreadcrumbs = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[firebase]
  apiKey = "AIzaSyAM9FxWgUA01vArRvgM5Ta2U087ADaqX5k"
  authDomain = "leorium-com.firebaseapp.com"
  projectId = "leorium-com"
  storageBucket = "leorium-com.firebasestorage.app"
  messagingSenderId = "633731080737"
  appId = "1:633731080737:web:26b8c455dfe1bec98ab960"
  measurementId = "G-YX346X3157"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  mainSections = ["blog"]
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showViews = true
  showLikes = true
  showComments = false
  showRelatedContent = true
  relatedContentLimit = 3
  showSummary = true
  seriesOpened = false
  showZenMode = false
  sharingLinks = [
    "twitter", "reddit", "linkedin", "email"
  ]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  groupByYear = true
  cardView = false
  showCards = false

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true
  cardView = false

[term]
  showBreadcrumbs = true
  groupByYear = true
  cardView = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
